spring.application.name=project
server.port=7350
#configuration JDBC connection properties
Spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=JDBC:MySql://localHost:3306/project?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
#configuration some addtional properties
#e.g enabling show sql,HBM 2 DDL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
debug=true
